version: '3'
services:
  fleetstate-server:
    build:
      context: .
    image: varankinv/ree-fleet-sim:latest
    command:
      - '/bin/fleetstate-server'
      - '-http-addr=:10080'
    ports:
      - '10080:10080'

  simulator:
    build:
      context: .
    image: varankinv/ree-fleet-sim:latest
    command: 
      - '/bin/simulator'
      - '-vehicles-total=20'
      - '-fleetstate-server-addr=http://fleetstate-server:10080/'
